export const UserConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    FETCH_PROFILE_REQUEST:"FETCH_PROFILE",
    FETCH_PROFILE_SUCCESS: "PROFILE_SUCCESS",
    FETCH_PROFILE_FAILURE:"PROFILE_FAILURE",


    LOGOUT_REQUEST: 'USERS_LOGOUT',
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE",

    ACTIVATE_REQUEST: 'ACCOUNT_ACTIVATE',
    ACTIVATE_SUCCESS: 'ACCOUNT_ACTIVATE_SUCCESS',
    ACTIVATE_FAILURE: 'ACCOUNT_ACTIVATE_FAILURE',

    RESET_PASSWORD_REQUEST:'RESET_PASSWORD',
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE:'RESET_PASSWORD_FAILURE',

    RESET_PASSWORD_CONFIRM_REQUEST:'RESET_PASSWORD_CONFIRM',
    RESET_PASSWORD_CONFIRM_SUCCESS:'RESET_PASSWORD_CONFIRM_SUCCESS',
    RESET_PASSWORD_CONFIRM_FAILURE:'RESET_PASSWORD_CONFIRM_FAILURE',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};